[tool.poetry]
name = "indicators"
version = "0.1.0"
description = ""
authors = ["Alpha <piotr@piotryordanov.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ta-lib = "^0.4.28"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
